#pragma once

#include "layer_alternatives.h"

#if !defined(HLOIREA_LAYER_BASE)
  #define HLOIREA_LAYER_BASE HLOIREA_ALTERNATIVES_BASE_QWERTY
#endif
#if !defined(HLOIREA_LAYERMAPPING_BASE)
  #define HLOIREA_LAYERMAPPING_BASE HLOIREA_MAPPING
#endif

#if !defined(HLOIREA_LAYER_NAV)
  #define HLOIREA_LAYER_NAV HLOIREA_ALTERNATIVES_NAV
#endif
#if !defined(HLOIREA_LAYERMAPPING_NAV)
  #define HLOIREA_LAYERMAPPING_NAV HLOIREA_MAPPING
#endif

#if !defined(HLOIREA_LAYER_NUM)
  #define HLOIREA_LAYER_NUM HLOIREA_ALTERNATIVES_NUM
#endif
#if !defined(HLOIREA_LAYERMAPPING_NUM)
  #define HLOIREA_LAYERMAPPING_NUM HLOIREA_MAPPING
#endif

#if !defined(HLOIREA_LAYER_SYM)
  #define HLOIREA_LAYER_SYM HLOIREA_ALTERNATIVES_SYM
#endif
#if !defined(HLOIREA_LAYERMAPPING_SYM)
  #define HLOIREA_LAYERMAPPING_SYM HLOIREA_MAPPING
#endif

#if !defined(HLOIREA_LAYER_FUN)
  #define HLOIREA_LAYER_FUN HLOIREA_ALTERNATIVES_FUN
#endif
#if !defined(HLOIREA_LAYERMAPPING_FUN)
  #define HLOIREA_LAYERMAPPING_FUN HLOIREA_MAPPING
#endif
