name: Build QMK firmware (36_charybdis)
on:
  workflow_dispatch:
  push:
    branches:
    - "layout_36_charybdis"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: hloirea/qmk_firmware
        ref: layout_36_charybdis
        submodules: recursive

    - name: Build firmware
      run: qmk compile -kb handwired/hloirea -km ${{ github.actor }}

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: handwired_hloirea_${{ github.actor }}_rp2040
        path: |
          *.hex
          *.bin
          *.uf2
