name: Build QMK firmware (dz60)
on:
  workflow_dispatch:
  push:
    branches:
    - "layout_42_corne"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: hloirea/qmk_firmware
        ref: layout_42_corne
        submodules: recursive

    - name: Build firmware
      run: qmk compile -kb crkbd/rev1 -km ${{ github.actor }} -e CONVERT_TO=promicro_rp2040

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: crkbd_rev1_${{ github.actor }}_promicro_rp2040
        path: |
          *.hex
          *.bin
          *.uf2
